
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'altimate_code_demos'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'altimate_code_demos'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  altimate_code_demos:
    raw_orders:
      +column_types:
        customer_id: varchar(10)
        amount: varchar(20)
    raw_payments:
      +column_types:
        amount: varchar(20)
        tax_amount: varchar(20)
    raw_products:
      +column_types:
        price: varchar(20)
        is_active: varchar(10)

models:
  altimate_code_demos:
    staging:
      +materialized: view
    marts:
      +materialized: table
